[[processes]]
command = ["ls", "-lh", "--color=auto"]

[[processes]]
command = ["echo", "one", "two", "three"]

[[processes]]
name = "Print and sleep"
command  = ["bash", "-c", "while :; do date; sleep 1; done"]

[[processes]]
name = "No autostart"
command  = ["bash", "-c", "while :; do date; sleep 1; done"]
autostart = false
