name: Build

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@1.78.0
      with:
        targets: x86_64-unknown-linux-musl,x86_64-pc-windows-gnu,x86_64-apple-darwin,aarch64-apple-darwin

    - run: sudo apt-get install --yes --no-install-recommends gcc-mingw-w64-x86-64-win32

    - uses: Timmmm/setup-osxcross@v3
      with:
        osx-version: "12.3"

    - run: |
        cargo build --release \
          --target x86_64-unknown-linux-musl \
          --target x86_64-pc-windows-gnu
        du -h target

    - uses: actions/upload-artifact@v4
      with:
        path: |
          target/x86_64-pc-windows-gnu/release/mintaka.exe
          target/x86_64-unknown-linux-musl/release/mintaka
